/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/9O6MfsB9sTP
 */


export function Component() {
  return (
    <footer className="bg-[#0d3b66] text-white">
      <div className="container mx-auto px-4 py-8 lg:flex lg:justify-between lg:items-start">
        <div className="mb-6 lg:mb-0">
          <h5 className="font-bold mb-4">Quick Links</h5>
          <ul className="space-y-2">
            <li>
              <a className="hover:underline" href="#">
                Home
              </a>
            </li>
            <li>
              <a className="hover:underline" href="#">
                Placements
              </a>
            </li>
            <li>
              <a className="hover:underline" href="#">
                Gallery
              </a>
            </li>
            <li>
              <a className="hover:underline" href="#">
                Registration
              </a>
            </li>
            <li>
              <a className="hover:underline" href="#">
                Registered Users
              </a>
            </li>
          </ul>
        </div>
        <div className="mb-6 lg:mb-0">
          <h5 className="font-bold mb-4">Facilities</h5>
          <ul className="space-y-2">
            <li>
              <a className="hover:underline" href="#">
                Hostel
              </a>
            </li>
            <li>
              <a className="hover:underline" href="#">
                Library
              </a>
            </li>
            <li>
              <a className="hover:underline" href="#">
                Cafeteria
              </a>
            </li>
            <li>
              <a className="hover:underline" href="#">
                Sports
              </a>
            </li>
          </ul>
        </div>
        <div className="mb-6 lg:mb-0">
          <h5 className="font-bold mb-4">Departments</h5>
          <ul className="space-y-2">
            <li>
              <a className="hover:underline" href="#">
                Artificial Intelligence and machine Learning
              </a>
            </li>
            <li>
              <a className="hover:underline" href="#">
                Civil Engineering
              </a>
            </li>
            <li>
              <a className="hover:underline" href="#">
                Computer Engineering
              </a>
            </li>
            <li>
              <a className="hover:underline" href="#">
                Electronics & Communication Engineering
              </a>
            </li>
            <li>
              <a className="hover:underline" href="#">
                Electrical and Electronics Engineering
              </a>
            </li>
            <li>
              <a className="hover:underline" href="#">
                Mechanical Engineering
              </a>
            </li>
          </ul>
        </div>
        <div className="mb-6 lg:mb-0">
          <h5 className="font-bold mb-4">Our About</h5>
          <ul className="space-y-2">
            <li>
              <a className="hover:underline" href="#">
                About Us
              </a>
            </li>
            <li>
              <a className="hover:underline" href="#">
                History
              </a>
            </li>
            <li>
              <a className="hover:underline" href="#">
                Management
              </a>
            </li>
            <li>
              <a className="hover:underline" href="#">
                Award and Honours
              </a>
            </li>
            <li>
              <a className="hover:underline" href="#">
                Distinctions
              </a>
            </li>
            <li>
              <a className="hover:underline" href="#">
                Events
              </a>
            </li>
            <li>
              <a className="hover:underline" href="#">
                LMS
              </a>
            </li>
          </ul>
        </div>
        <div className="mb-6 lg:mb-0">
          <h5 className="font-bold mb-4">Achievements</h5>
          <ul className="space-y-2">
            <li>
              <a className="hover:underline" href="#">
                Bank rankers
              </a>
            </li>
            <li>
              <a className="hover:underline" href="#">
                State Rankers
              </a>
            </li>
            <li>
              <a className="hover:underline" href="#">
                ECET Rankers
              </a>
            </li>
            <li>
              <a className="hover:underline" href="#">
                Prathiba Awards
              </a>
            </li>
            <li>
              <a className="hover:underline" href="#">
                Sports Shine
              </a>
            </li>
            <li>
              <a className="hover:underline" href="#">
                National Level Prizes
              </a>
            </li>
            <li>
              <a className="hover:underline" href="#">
                State Level Prizes
              </a>
            </li>
          </ul>
        </div>
      </div>
      <div className="bg-[#e76f51] py-4">
        <p className="text-center text-sm">© 2023 AANM-VVRSR polytechnic College . Powered By Topnotch</p>
      </div>
    </footer>
  )
}
